export interface REFERENCIA   {
    D1 ?:  number,
    D2 ?:  number,
    D3 ?:  number,
    D4 ?:  number,
    D5 ?:  number,
    D6 ?:  number,
    D7 ?:  number,
    D8 ?:  number,
    D9 ?:  number,
    D10?:  number,
    D11?:  number,
    D12?:  number,
    D13?:  number,
    D14?:  number,
    D15?:  number,
    D16?:  number,
    D17?:  number,
    D18?:  number,
    D19?:  number,
    D20?:  number,
    D21?:  number,
    D22?:  number,
    D23?:  number,
    D24?:  number,
    D25?:  number,
    D26?:  number,
    D27?:  number,
    D28?:  number,
    D29?:  number,
    D30?:  number,
    D31?:  number,
    D32?:  number,
    D33?:  number,
    D34?:  number,
    D35?:  number,
    D36?:  number,
    D37?:  number,
    D38?:  number,
    D39?:  number
}